server {
    listen 80;

    # 1. Исправленный корневой локейшен (для фронтенда)
    location / {
        root /staticfiles/; # Теперь Nginx будет искать фронтенд здесь без багов
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Локейшен для статики (чтобы у админки Django были стили и картинки)
    location /static/ {
        root /staticfiles/;
    }

    # 3. Перенаправление на бэкенд для API
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_pass http://backend:8000; 
    }

    # 4. Перенаправление на бэкенд для Админки
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_pass http://backend:8000;
    }
}
